# COPYRIGHT Hello Corp. All Rights Reserved.
# 
# Author: Haley
#

version: '2'

services:

  zookeeper:
    image: hyperledger/fabric-zookeeper:0.4.10
    restart: always
#    environment:
#      - quorumListenOnAllIPs=true
#    ports:
#      - '2181'
#      - '2888'
#      - '3888'
    networks:
      - default

  kafka:
    image: hyperledger/fabric-kafka:0.4.10
    restart: always
    environment:
      # message.max.bytes
      # The maximum size of envelope that the broker can receive.
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
#    ports:
#      - '9092'
    networks:
      - default
